// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entities.Migrations
{
    [DbContext(typeof(TimeContext))]
    [Migration("20250707173941_Db_Created")]
    partial class Db_Created
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Admin", b =>
                {
                    b.Property<long>("AdminID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AdminID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdminID");

                    b.ToTable("AdminTbl");
                });

            modelBuilder.Entity("Core.Area", b =>
                {
                    b.Property<long>("AreaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AreaID"));

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CityID")
                        .HasColumnType("bigint");

                    b.HasKey("AreaID");

                    b.HasIndex("CityID");

                    b.ToTable("AreaTbl");
                });

            modelBuilder.Entity("Core.BookedAppPayment", b =>
                {
                    b.Property<long>("BookedAppointmentPaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BookedAppointmentPaymentID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("BookedAppointmentID")
                        .HasColumnType("bigint");

                    b.Property<int>("PaymentMode")
                        .HasColumnType("int");

                    b.HasKey("BookedAppointmentPaymentID");

                    b.HasIndex("BookedAppointmentID");

                    b.ToTable("BookedAppPaymentTbl");
                });

            modelBuilder.Entity("Core.BookedAppointment", b =>
                {
                    b.Property<long>("BookedAppointmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BookedAppointmentID"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("DoctorScheduleID")
                        .HasColumnType("bigint");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<long>("PatientID")
                        .HasColumnType("bigint");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookedAppointmentID");

                    b.HasIndex("DoctorScheduleID");

                    b.HasIndex("PatientID");

                    b.ToTable("BookedAppointmentTbl");
                });

            modelBuilder.Entity("Core.City", b =>
                {
                    b.Property<long>("CityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CityID"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("StateID")
                        .HasColumnType("bigint");

                    b.HasKey("CityID");

                    b.HasIndex("StateID");

                    b.ToTable("CityTbl");
                });

            modelBuilder.Entity("Core.Clinic", b =>
                {
                    b.Property<long>("ClinicID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ClinicID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CityID")
                        .HasColumnType("bigint");

                    b.Property<string>("ClinicName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPersonName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LandLineNO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logopath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("WebsiteUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClinicID");

                    b.HasIndex("CityID");

                    b.ToTable("ClinicTbl");
                });

            modelBuilder.Entity("Core.ClinicAdmin", b =>
                {
                    b.Property<long>("ClinicAdminID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ClinicAdminID"));

                    b.Property<long>("ClinicID")
                        .HasColumnType("bigint");

                    b.Property<string>("EmailID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClinicAdminID");

                    b.HasIndex("ClinicID");

                    b.ToTable("ClinicAdminTbl");
                });

            modelBuilder.Entity("Core.ClinicCertificate", b =>
                {
                    b.Property<long>("ClinicCertificateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ClinicCertificateID"));

                    b.Property<DateTime>("CertificateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CertificateName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ClinicID")
                        .HasColumnType("bigint");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClinicCertificateID");

                    b.HasIndex("ClinicID");

                    b.ToTable("ClinicCertificateTbl");
                });

            modelBuilder.Entity("Core.ClinicFacility", b =>
                {
                    b.Property<long>("ClinicFacilityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ClinicFacilityID"));

                    b.Property<string>("ClinicFacilityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ClinicID")
                        .HasColumnType("bigint");

                    b.HasKey("ClinicFacilityID");

                    b.HasIndex("ClinicID");

                    b.ToTable("ClinicFacilityTbl");
                });

            modelBuilder.Entity("Core.ClinicRating", b =>
                {
                    b.Property<long>("ClinicRatingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ClinicRatingID"));

                    b.Property<long>("ClinicID")
                        .HasColumnType("bigint");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("ClinicRatingID");

                    b.HasIndex("ClinicID");

                    b.HasIndex("UserID");

                    b.ToTable("ClinicRatingTbl");
                });

            modelBuilder.Entity("Core.Country", b =>
                {
                    b.Property<long>("CountryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CountryID"));

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryID");

                    b.ToTable("CountryTbl");
                });

            modelBuilder.Entity("Core.Doctor", b =>
                {
                    b.Property<long>("DoctorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DoctorID"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("AreaID")
                        .HasColumnType("bigint");

                    b.Property<long>("ClinicID")
                        .HasColumnType("bigint");

                    b.Property<string>("DoctorExperiance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoctorQualification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("VisitingCharges")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("DoctorID");

                    b.HasIndex("AreaID");

                    b.HasIndex("ClinicID");

                    b.ToTable("DoctorTbl");
                });

            modelBuilder.Entity("Core.DoctorClinicSession", b =>
                {
                    b.Property<long>("DoctorClinicSessionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DoctorClinicSessionID"));

                    b.Property<long>("ClinicID")
                        .HasColumnType("bigint");

                    b.Property<long>("DoctorID")
                        .HasColumnType("bigint");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("OPDSessionID")
                        .HasColumnType("bigint");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TimeInterval")
                        .HasColumnType("int");

                    b.HasKey("DoctorClinicSessionID");

                    b.HasIndex("ClinicID");

                    b.HasIndex("DoctorID");

                    b.HasIndex("OPDSessionID");

                    b.ToTable("DoctorClinicSessionTbl");
                });

            modelBuilder.Entity("Core.DoctorRating", b =>
                {
                    b.Property<long>("DoctorRatingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DoctorRatingID"));

                    b.Property<long>("DoctorID")
                        .HasColumnType("bigint");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("DoctorRatingID");

                    b.HasIndex("DoctorID");

                    b.HasIndex("UserID");

                    b.ToTable("DoctorRatingTbl");
                });

            modelBuilder.Entity("Core.DoctorSchedule", b =>
                {
                    b.Property<long>("DoctorScheduleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DoctorScheduleID"));

                    b.Property<long>("DayOfWeek")
                        .HasColumnType("bigint");

                    b.Property<long>("DoctorID")
                        .HasColumnType("bigint");

                    b.Property<string>("EndTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Interval")
                        .HasColumnType("bigint");

                    b.Property<long>("OPDSessionID")
                        .HasColumnType("bigint");

                    b.Property<string>("StartTime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DoctorScheduleID");

                    b.HasIndex("DoctorID");

                    b.HasIndex("OPDSessionID");

                    b.ToTable("DcotorScheduleTbl");
                });

            modelBuilder.Entity("Core.DoctorSpeciality", b =>
                {
                    b.Property<long>("DoctorSpecialityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DoctorSpecialityID"));

                    b.Property<long>("DoctorID")
                        .HasColumnType("bigint");

                    b.Property<long>("SpecilityID")
                        .HasColumnType("bigint");

                    b.HasKey("DoctorSpecialityID");

                    b.HasIndex("DoctorID");

                    b.HasIndex("SpecilityID");

                    b.ToTable("DoctorSpecialityTbl");
                });

            modelBuilder.Entity("Core.Medicine", b =>
                {
                    b.Property<long>("MedicineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MedicineID"));

                    b.Property<DateTime>("ExpDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MedicineName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MfgDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MfgName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MedicineID");

                    b.ToTable("MedicineTbl");
                });

            modelBuilder.Entity("Core.OPDSession", b =>
                {
                    b.Property<long>("OPDSessionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OPDSessionID"));

                    b.Property<long>("ClinicID")
                        .HasColumnType("bigint");

                    b.Property<string>("SessionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OPDSessionID");

                    b.HasIndex("ClinicID");

                    b.ToTable("OPDSessionTbl");
                });

            modelBuilder.Entity("Core.Patient", b =>
                {
                    b.Property<long>("PatientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PatientID"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("PatientID");

                    b.HasIndex("UserID");

                    b.ToTable("PatientTbl");
                });

            modelBuilder.Entity("Core.Prescription", b =>
                {
                    b.Property<long>("PrescriptionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PrescriptionID"));

                    b.Property<long>("BookedAppointmentID")
                        .HasColumnType("bigint");

                    b.Property<long>("DoctorID")
                        .HasColumnType("bigint");

                    b.Property<long>("PatientID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("PrescriptionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PrescriptionID");

                    b.HasIndex("BookedAppointmentID");

                    b.HasIndex("DoctorID");

                    b.HasIndex("PatientID");

                    b.ToTable("PrescriptionTbl");
                });

            modelBuilder.Entity("Core.PrescriptionDetail", b =>
                {
                    b.Property<long>("PrescriptionDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PrescriptionDetailID"));

                    b.Property<long>("Dosage")
                        .HasColumnType("bigint");

                    b.Property<string>("Duration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("MedicineID")
                        .HasColumnType("bigint");

                    b.Property<long>("PrescriptionID")
                        .HasColumnType("bigint");

                    b.Property<long>("Qty")
                        .HasColumnType("bigint");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PrescriptionDetailID");

                    b.HasIndex("MedicineID");

                    b.HasIndex("PrescriptionID");

                    b.ToTable("PrescriptionDetailTbl");
                });

            modelBuilder.Entity("Core.Specility", b =>
                {
                    b.Property<long>("SpecilityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SpecilityID"));

                    b.Property<string>("SpecilityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SpecilityID");

                    b.ToTable("SpecilityTbl");
                });

            modelBuilder.Entity("Core.State", b =>
                {
                    b.Property<long>("StateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("StateID"));

                    b.Property<long>("CountryID")
                        .HasColumnType("bigint");

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StateID");

                    b.HasIndex("CountryID");

                    b.ToTable("StateTbl");
                });

            modelBuilder.Entity("Core.User", b =>
                {
                    b.Property<long>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CountryID")
                        .HasColumnType("bigint");

                    b.Property<string>("EmailID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.HasIndex("CountryID");

                    b.ToTable("UserTbl");
                });

            modelBuilder.Entity("Core.Area", b =>
                {
                    b.HasOne("Core.City", "City")
                        .WithMany("Area")
                        .HasForeignKey("CityID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Core.BookedAppPayment", b =>
                {
                    b.HasOne("Core.BookedAppointment", "BookedAppointment")
                        .WithMany("BookedAppPayments")
                        .HasForeignKey("BookedAppointmentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BookedAppointment");
                });

            modelBuilder.Entity("Core.BookedAppointment", b =>
                {
                    b.HasOne("Core.DoctorSchedule", "DoctorSchedule")
                        .WithMany("BookedAppointment")
                        .HasForeignKey("DoctorScheduleID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Patient", "Patient")
                        .WithMany("BookedAppointments")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DoctorSchedule");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Core.City", b =>
                {
                    b.HasOne("Core.State", "State")
                        .WithMany("Cities")
                        .HasForeignKey("StateID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("Core.Clinic", b =>
                {
                    b.HasOne("Core.City", "City")
                        .WithMany("Clinic")
                        .HasForeignKey("CityID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Core.ClinicAdmin", b =>
                {
                    b.HasOne("Core.Clinic", "Clinic")
                        .WithMany("clinicAdmins")
                        .HasForeignKey("ClinicID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("Core.ClinicCertificate", b =>
                {
                    b.HasOne("Core.Clinic", "Clinic")
                        .WithMany("ClinicCertificates")
                        .HasForeignKey("ClinicID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("Core.ClinicFacility", b =>
                {
                    b.HasOne("Core.Clinic", "Clinic")
                        .WithMany("ClinicFacilities")
                        .HasForeignKey("ClinicID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("Core.ClinicRating", b =>
                {
                    b.HasOne("Core.Clinic", "Clinic")
                        .WithMany("ClinicRatings")
                        .HasForeignKey("ClinicID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.User", "User")
                        .WithMany("ClinicRatings")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Clinic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Doctor", b =>
                {
                    b.HasOne("Core.Area", "Area")
                        .WithMany("Doctors")
                        .HasForeignKey("AreaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Clinic", "Clinic")
                        .WithMany("Doctors")
                        .HasForeignKey("ClinicID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("Core.DoctorClinicSession", b =>
                {
                    b.HasOne("Core.Clinic", "Clinic")
                        .WithMany("DoctorClinicSessions")
                        .HasForeignKey("ClinicID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Doctor", "Doctor")
                        .WithMany("DoctorClinicSessions")
                        .HasForeignKey("DoctorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.OPDSession", "OPDSession")
                        .WithMany("DoctorClinicSessions")
                        .HasForeignKey("OPDSessionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Clinic");

                    b.Navigation("Doctor");

                    b.Navigation("OPDSession");
                });

            modelBuilder.Entity("Core.DoctorRating", b =>
                {
                    b.HasOne("Core.Doctor", "Doctor")
                        .WithMany("DoctorRatings")
                        .HasForeignKey("DoctorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.User", "User")
                        .WithMany("DoctorRatings")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.DoctorSchedule", b =>
                {
                    b.HasOne("Core.Doctor", "Doctor")
                        .WithMany("DoctorSchedules")
                        .HasForeignKey("DoctorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.OPDSession", "OpdSession")
                        .WithMany("DoctorSchedules")
                        .HasForeignKey("OPDSessionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("OpdSession");
                });

            modelBuilder.Entity("Core.DoctorSpeciality", b =>
                {
                    b.HasOne("Core.Doctor", "Doctor")
                        .WithMany("DoctorSpecialities")
                        .HasForeignKey("DoctorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Specility", "Specility")
                        .WithMany("DoctorSpecialities")
                        .HasForeignKey("SpecilityID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Specility");
                });

            modelBuilder.Entity("Core.OPDSession", b =>
                {
                    b.HasOne("Core.Clinic", "Clinic")
                        .WithMany("OPDSessions")
                        .HasForeignKey("ClinicID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("Core.Patient", b =>
                {
                    b.HasOne("Core.User", "User")
                        .WithMany("Patients")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Prescription", b =>
                {
                    b.HasOne("Core.BookedAppointment", "BookedAppointment")
                        .WithMany("Prescriptions")
                        .HasForeignKey("BookedAppointmentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Doctor", "Doctor")
                        .WithMany("Prescriptions")
                        .HasForeignKey("DoctorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Patient", "Patient")
                        .WithMany("Prescriptions")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BookedAppointment");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Core.PrescriptionDetail", b =>
                {
                    b.HasOne("Core.Medicine", "Medicine")
                        .WithMany("PrescriptionDetails")
                        .HasForeignKey("MedicineID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Prescription", "Prescription")
                        .WithMany("PrescriptionDetail")
                        .HasForeignKey("PrescriptionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Medicine");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("Core.State", b =>
                {
                    b.HasOne("Core.Country", "Country")
                        .WithMany("States")
                        .HasForeignKey("CountryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Core.User", b =>
                {
                    b.HasOne("Core.Country", "Country")
                        .WithMany("Users")
                        .HasForeignKey("CountryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Core.Area", b =>
                {
                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("Core.BookedAppointment", b =>
                {
                    b.Navigation("BookedAppPayments");

                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("Core.City", b =>
                {
                    b.Navigation("Area");

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("Core.Clinic", b =>
                {
                    b.Navigation("ClinicCertificates");

                    b.Navigation("ClinicFacilities");

                    b.Navigation("ClinicRatings");

                    b.Navigation("DoctorClinicSessions");

                    b.Navigation("Doctors");

                    b.Navigation("OPDSessions");

                    b.Navigation("clinicAdmins");
                });

            modelBuilder.Entity("Core.Country", b =>
                {
                    b.Navigation("States");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Core.Doctor", b =>
                {
                    b.Navigation("DoctorClinicSessions");

                    b.Navigation("DoctorRatings");

                    b.Navigation("DoctorSchedules");

                    b.Navigation("DoctorSpecialities");

                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("Core.DoctorSchedule", b =>
                {
                    b.Navigation("BookedAppointment");
                });

            modelBuilder.Entity("Core.Medicine", b =>
                {
                    b.Navigation("PrescriptionDetails");
                });

            modelBuilder.Entity("Core.OPDSession", b =>
                {
                    b.Navigation("DoctorClinicSessions");

                    b.Navigation("DoctorSchedules");
                });

            modelBuilder.Entity("Core.Patient", b =>
                {
                    b.Navigation("BookedAppointments");

                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("Core.Prescription", b =>
                {
                    b.Navigation("PrescriptionDetail");
                });

            modelBuilder.Entity("Core.Specility", b =>
                {
                    b.Navigation("DoctorSpecialities");
                });

            modelBuilder.Entity("Core.State", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("Core.User", b =>
                {
                    b.Navigation("ClinicRatings");

                    b.Navigation("DoctorRatings");

                    b.Navigation("Patients");
                });
#pragma warning restore 612, 618
        }
    }
}
